import sqlite3
import asyncio
from db import insertFacts

con = sqlite3.connect("cat_facts.db")

cur = con.cursor()
#Both, id and date are autogenerated
cur.execute("CREATE TABLE IF NOT EXISTS cat_facts (id INTEGER PRIMARY KEY AUTOINCREMENT, fact TEXT UNIQUE, created_at DATE DEFAULT (DATE('now')))")
con.commit()

asyncio.run(insertFacts(cur, con))